local wg = require("window_groups")

-- Ensure exclude set is populated with defaults
wg.config.exclude_filetypes = {}
-- Build exclude set by calling setup (idempotent guard skips double-init;
-- call internal build directly for test isolation)
pcall(function()
	wg.setup({})
end)

describe("eligible()", function()
	it("returns false for invalid buf", function()
		assert.is_false(wg.eligible(99999))
	end)

	it("returns false for buf with non-empty buftype", function()
		local buf = vim.api.nvim_create_buf(false, true)
		vim.bo[buf].buftype = "nofile"
		assert.is_false(wg.eligible(buf))
		vim.api.nvim_buf_delete(buf, { force = true })
	end)

	it("returns false for unlisted buf", function()
		local buf = vim.api.nvim_create_buf(false, false)
		assert.is_false(wg.eligible(buf))
		vim.api.nvim_buf_delete(buf, { force = true })
	end)

	it("returns true for normal listed buf", function()
		local buf = vim.api.nvim_create_buf(true, false)
		assert.is_true(wg.eligible(buf))
		vim.api.nvim_buf_delete(buf, { force = true })
	end)

	it("returns false for excluded filetype", function()
		local buf = vim.api.nvim_create_buf(true, false)
		vim.bo[buf].filetype = "neo-tree"
		assert.is_false(wg.eligible(buf))
		vim.api.nvim_buf_delete(buf, { force = true })
	end)
end)

describe("add() / list() / remove()", function()
	it("adds buf to window group", function()
		local buf = vim.api.nvim_create_buf(true, false)
		local win = vim.api.nvim_get_current_win()
		vim.api.nvim_win_set_var(win, "group_bufs", {})
		wg.add(win, buf)
		assert.is_true(vim.tbl_contains(wg.list(win), buf))
		vim.api.nvim_buf_delete(buf, { force = true })
	end)

	it("does not add same buf twice", function()
		local buf = vim.api.nvim_create_buf(true, false)
		local win = vim.api.nvim_get_current_win()
		vim.api.nvim_win_set_var(win, "group_bufs", {})
		wg.add(win, buf)
		wg.add(win, buf)
		local count = 0
		for _, b in ipairs(wg.list(win)) do
			if b == buf then count = count + 1 end
		end
		assert.equals(1, count)
		vim.api.nvim_buf_delete(buf, { force = true })
	end)

	it("removes buf from group", function()
		local buf = vim.api.nvim_create_buf(true, false)
		local win = vim.api.nvim_get_current_win()
		vim.api.nvim_win_set_var(win, "group_bufs", { buf })
		wg.remove(win, buf)
		assert.is_false(vim.tbl_contains(wg.list(win), buf))
		vim.api.nvim_buf_delete(buf, { force = true })
	end)

	it("does not error when removing buf not in group", function()
		local buf = vim.api.nvim_create_buf(true, false)
		local win = vim.api.nvim_get_current_win()
		vim.api.nvim_win_set_var(win, "group_bufs", {})
		assert.has_no_error(function() wg.remove(win, buf) end)
		vim.api.nvim_buf_delete(buf, { force = true })
	end)
end)

describe("find_owner()", function()
	it("returns the window owning a buf", function()
		local buf = vim.api.nvim_create_buf(true, false)
		local win = vim.api.nvim_get_current_win()
		vim.api.nvim_win_set_var(win, "group_bufs", { buf })
		assert.equals(win, wg.find_owner(buf))
		vim.api.nvim_buf_delete(buf, { force = true })
	end)

	it("returns nil for buf not in any group", function()
		local buf = vim.api.nvim_create_buf(true, false)
		-- Ensure no window claims this buf
		for _, win in ipairs(vim.api.nvim_tabpage_list_wins(0)) do
			vim.api.nvim_win_set_var(win, "group_bufs", {})
		end
		assert.is_nil(wg.find_owner(buf))
		vim.api.nvim_buf_delete(buf, { force = true })
	end)
end)

describe("cycle()", function()
	it("advances to next buf in group", function()
		local win = vim.api.nvim_get_current_win()
		local buf1 = vim.api.nvim_create_buf(true, false)
		local buf2 = vim.api.nvim_create_buf(true, false)
		vim.api.nvim_win_set_buf(win, buf1)
		vim.api.nvim_win_set_var(win, "group_bufs", { buf1, buf2 })
		wg.cycle("next")
		assert.equals(buf2, vim.api.nvim_win_get_buf(win))
		vim.api.nvim_buf_delete(buf1, { force = true })
		vim.api.nvim_buf_delete(buf2, { force = true })
	end)

	it("wraps from last to first", function()
		local win = vim.api.nvim_get_current_win()
		local buf1 = vim.api.nvim_create_buf(true, false)
		local buf2 = vim.api.nvim_create_buf(true, false)
		vim.api.nvim_win_set_buf(win, buf2)
		vim.api.nvim_win_set_var(win, "group_bufs", { buf1, buf2 })
		wg.cycle("next")
		assert.equals(buf1, vim.api.nvim_win_get_buf(win))
		vim.api.nvim_buf_delete(buf1, { force = true })
		vim.api.nvim_buf_delete(buf2, { force = true })
	end)

	it("does nothing with fewer than 2 bufs", function()
		local win = vim.api.nvim_get_current_win()
		local buf = vim.api.nvim_create_buf(true, false)
		vim.api.nvim_win_set_buf(win, buf)
		vim.api.nvim_win_set_var(win, "group_bufs", { buf })
		wg.cycle("next")
		assert.equals(buf, vim.api.nvim_win_get_buf(win))
		vim.api.nvim_buf_delete(buf, { force = true })
	end)
end)

describe("last_buf()", function()
	it("returns the last valid buf", function()
		local win = vim.api.nvim_get_current_win()
		local buf1 = vim.api.nvim_create_buf(true, false)
		local buf2 = vim.api.nvim_create_buf(true, false)
		vim.api.nvim_win_set_var(win, "group_bufs", { buf1, buf2 })
		assert.equals(buf2, wg.last_buf(win))
		vim.api.nvim_buf_delete(buf1, { force = true })
		vim.api.nvim_buf_delete(buf2, { force = true })
	end)

	it("returns nil for empty group", function()
		local win = vim.api.nvim_get_current_win()
		vim.api.nvim_win_set_var(win, "group_bufs", {})
		assert.is_nil(wg.last_buf(win))
	end)
end)
