local winbar = require("window_groups.winbar")

describe("winbar.render()", function()
	it("returns empty string when buftype is not ''", function()
		local buf = vim.api.nvim_create_buf(false, true)
		vim.bo[buf].buftype = "nofile"
		local win = vim.api.nvim_get_current_win()
		vim.api.nvim_win_set_buf(win, buf)
		vim.api.nvim_win_set_var(win, "group_bufs", {})
		assert.equals("", winbar.render())
		vim.api.nvim_buf_delete(buf, { force = true })
	end)

	it("returns empty string when group is empty", function()
		local buf = vim.api.nvim_create_buf(true, false)
		local win = vim.api.nvim_get_current_win()
		vim.api.nvim_win_set_buf(win, buf)
		vim.api.nvim_win_set_var(win, "group_bufs", {})
		assert.equals("", winbar.render())
		vim.api.nvim_buf_delete(buf, { force = true })
	end)

	it("returns non-empty string for non-empty group", function()
		local buf = vim.api.nvim_create_buf(true, false)
		local win = vim.api.nvim_get_current_win()
		vim.api.nvim_win_set_buf(win, buf)
		vim.api.nvim_win_set_var(win, "group_bufs", { buf })
		local result = winbar.render()
		assert.is_true(result ~= "")
		vim.api.nvim_buf_delete(buf, { force = true })
	end)

	it("includes [No Name] for unnamed buf", function()
		local buf = vim.api.nvim_create_buf(true, false)
		local win = vim.api.nvim_get_current_win()
		vim.api.nvim_win_set_buf(win, buf)
		vim.api.nvim_win_set_var(win, "group_bufs", { buf })
		local result = winbar.render()
		assert.is_true(result:find("%[No Name%]") ~= nil)
		vim.api.nvim_buf_delete(buf, { force = true })
	end)

	it("includes modified marker for modified buf", function()
		local buf = vim.api.nvim_create_buf(true, false)
		vim.api.nvim_buf_set_lines(buf, 0, -1, false, { "dirty" })
		local win = vim.api.nvim_get_current_win()
		vim.api.nvim_win_set_buf(win, buf)
		vim.api.nvim_win_set_var(win, "group_bufs", { buf })
		local result = winbar.render()
		assert.is_true(result:find("●") ~= nil)
		vim.api.nvim_buf_delete(buf, { force = true })
	end)
end)
