local winbar = require("window_groups.winbar")

describe("winbar.render()", function()
	it("returns empty string when buftype is not ''", function()
		local buf = vim.api.nvim_create_buf(false, true)
		vim.bo[buf].buftype = "nofile"
		local win = vim.api.nvim_get_current_win()
		vim.api.nvim_win_set_buf(win, buf)
		vim.api.nvim_win_set_var(win, "group_bufs", {})
		assert.equals("", winbar.render())
		vim.api.nvim_buf_delete(buf, { force = true })
	end)

	it("returns empty string when group is empty", function()
		local buf = vim.api.nvim_create_buf(true, false)
		local win = vim.api.nvim_get_current_win()
		vim.api.nvim_win_set_buf(win, buf)
		vim.api.nvim_win_set_var(win, "group_bufs", {})
		assert.equals("", winbar.render())
		vim.api.nvim_buf_delete(buf, { force = true })
	end)

	it("returns non-empty string for non-empty group", function()
		local buf = vim.api.nvim_create_buf(true, false)
		local win = vim.api.nvim_get_current_win()
		vim.api.nvim_win_set_buf(win, buf)
		vim.api.nvim_win_set_var(win, "group_bufs", { buf })
		local result = winbar.render()
		assert.is_true(result ~= "")
		vim.api.nvim_buf_delete(buf, { force = true })
	end)

	it("includes [No Name] for unnamed buf", function()
		local buf = vim.api.nvim_create_buf(true, false)
		local win = vim.api.nvim_get_current_win()
		vim.api.nvim_win_set_buf(win, buf)
		vim.api.nvim_win_set_var(win, "group_bufs", { buf })
		local result = winbar.render()
		assert.is_true(result:find("%[No Name%]") ~= nil)
		vim.api.nvim_buf_delete(buf, { force = true })
	end)

	it("includes modified marker for modified buf", function()
		local buf = vim.api.nvim_create_buf(true, false)
		vim.api.nvim_buf_set_lines(buf, 0, -1, false, { "dirty" })
		local win = vim.api.nvim_get_current_win()
		vim.api.nvim_win_set_buf(win, buf)
		vim.api.nvim_win_set_var(win, "group_bufs", { buf })
		local result = winbar.render()
		assert.is_true(result:find("●") ~= nil)
		vim.api.nvim_buf_delete(buf, { force = true })
	end)

	it("makes buffer segments clickable", function()
		local buf = vim.api.nvim_create_buf(true, false)
		local win = vim.api.nvim_get_current_win()
		vim.api.nvim_win_set_buf(win, buf)
		vim.api.nvim_win_set_var(win, "group_bufs", { buf })
		local result = winbar.render()
		assert.is_true(result:find("%" .. buf .. "@v:lua.require'window_groups.winbar'.click@", 1, true) ~= nil)
		assert.is_true(result:find("%%T") ~= nil)
		vim.api.nvim_buf_delete(buf, { force = true })
	end)

	it("dispatches clicks to the configured callback", function()
		local buf = vim.api.nvim_create_buf(true, false)
		local win = vim.api.nvim_get_current_win()
		vim.api.nvim_win_set_buf(win, buf)
		vim.api.nvim_win_set_var(win, "group_bufs", { buf })
		local called
		local groups = require("window_groups")
		local original = groups.config.clicks
		groups.config.clicks = { left = function(clicked, clicks, button, modifiers)
			called = { clicked, clicks, button, modifiers }
		end }
		winbar.click(buf, 2, "l", "s")
		assert.same({ buf, 2, "l", "s" }, called)
		groups.config.clicks = original
		vim.api.nvim_buf_delete(buf, { force = true })
	end)

	it("selects a buffer with the default left click", function()
		local first = vim.api.nvim_create_buf(true, false)
		local second = vim.api.nvim_create_buf(true, false)
		local win = vim.api.nvim_get_current_win()
		vim.api.nvim_win_set_buf(win, first)
		vim.api.nvim_win_set_var(win, "group_bufs", { first, second })
		winbar.click(second, 1, "l", "")
		assert.equals(second, vim.api.nvim_win_get_buf(win))
		vim.api.nvim_buf_delete(first, { force = true })
		vim.api.nvim_buf_delete(second, { force = true })
	end)
end)
